### ISSUE TITLE
Move to Cloudlink JS 4

### ISSUE THREAD

**Issue by williamhorning** [meower-media-co/Meower-SvelteKit#10]
Instead of maintaining a custom version of CLJS 3, we should move Svelte and SvelteKit over to  [CLJS 4](https://www.npmjs.com/package/@williamhorning/cloudlink), which is on NPM and supports logging and reconnecting later on, all features added in the modified versions of CLJS. It also has actual types instead of JSDoc comments

**Comment by showierdata9978** [comment]
Currently Kit has custom types that would be a pain to move. Also, sveltekit is ts, so it has already converted jsdoc to typescript

**Comment by williamhorning** [comment]
This shouldn't be implemented right now since CLJS4 is meant for CL4, but it'd be a good idea to do this with the CL4 port

**Comment by showierdata9978** [comment]
Im going to move kit to CL4 as soon as the test server is up, so right now this is waiting on @MikeDev101 and @tnix100

**Comment by mdwalters** [comment]
BLocked

**Comment by showierdata9978** [comment]
Half blocked, as I have a dev server that I run, however that fails for other ppl
